database:
  host: "127.0.0.1"
  port: 5432
  user: "keycloak"
  password: "sf2025~SHENMA"
  dbname: "quota_manager"
  sslmode: "disable"

auth_database:
  host: "127.0.0.1"
  port: 5432
  user: "keycloak"
  password: "sf2025~SHENMA"
  dbname: "auth"
  sslmode: "disable"

aigateway:
  host: "127.0.0.1"
  port: 8002
  admin_path: "/v1/chat/completions/quota"
  auth_header: "x-admin-key"
  auth_value: "12345678"

server:
  port: 8099
  mode: "release"
  token_header: "authorization"
  timezone: "Asia/Shanghai"  # Beijing Time (UTC+8)

scheduler:
  scan_interval: "0 0 * * * *" # Scan every hour (6 fields: second minute hour day month weekday)

voucher:
  signing_key: "your-secret-signing-key-at-least-32-bytes-long-for-security"

log:
  level: "warn"

employee_sync:
  enabled: false
  hr_url: "http://localhost:8099/api/hr/employees"
  hr_key: "test-hr-key"
  dept_url: "http://localhost:8099/api/hr/departments"
  dept_key: "test-dept-key"

github_star_check:
  enabled: false  # 是否启用GitHub star检查
  required_repo: "sangfor/quota-manager"  # 需要star的项目